apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yai-nginx
  name: yai-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yai-nginx
  template:
    metadata:
      labels:
        app: yai-nginx
    spec:
      containers:
      - image: docker.io/yailiev/my-webserver:v3.4
        imagePullPolicy: Always
        name: yai-nginx
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
          - mountPath: /etc/nginx/conf.d
            name: config
            readOnly: true
      dnsPolicy: ClusterFirst
      volumes:
      - configMap:
          items:
          - key: default.conf
            path: default.conf
          name: nginx-configmap
        name: config
